blueprint:
  name: BP - Pico Config
  description: "This is for the 5 button picos that have the following model:\n\n
  PJ2-3BRL-GXX-X01 (Pico3ButtonRaiseLower)\n\nSelect an action for each button listed below. "
  domain: automation
  input:
    pico_remote:
      name: Pico Remote
      description: "Select the pico remote to configure:"
      selector:
        device:
          integration: lutron_caseta
          model: PJ2-3BRL-GXX-X01 (Pico3ButtonRaiseLower)
    auto_mode:
      name: Automation Mode
      description: "Mode that automation runs in (single,  restart, queued, parallel)."
      default: restart
      selector:
        select:
          options:
            - single
            - restart
            - queued
            - parallel
    mode_max:
      name: "Mode Max (ignored by Single and Restart Modes)"
      description: "Maximum number of runs that can be executed or queued at a time."
      default: 10
      selector:
        number:
          min: 1
          max: 15
    top_on:
      name: Top (On) Button Pressed
      description: "Execute when TOP button is PRESSED"
      default: []
      selector:
        action: {}
    top_on_release:
      name: Top (On) Button Released
      description: "Execute when TOP button is RELEASED"
      default: []
      selector:
        action: {}
    up_raise:
      name: Up (Raise) Arrow Button Pressed
      description: "Execute when UP button is PRESSED"
      default: []
      selector:
        action: {}
    up_raise_release:
      name: Up (Raise) Arrow Button Released
      description: "Execute when UP button is RELEASED"
      default: []
      selector:
        action: {}
    middle_stop:
      name: Middle (Fav) Button Pressed
      description: "Execute when MIDDLE button is PRESSED"
      default: []
      selector:
        action: {}
    middle_stop_release:
      name: Middle (Fav) Button Released
      description: "Execute when MIDDLE button is RELEASED"
      default: []
      selector:
        action: {}
    down_lower:
      name: Down (Lower) Arrow Button Pressed
      description: "Execute when DOWN button is PRESSED"
      default: []
      selector:
        action: {}
    down_lower_release:
      name: Down (Lower) Arrow Button Released
      description: "Execute when DOWN button is RELEASED"
      default: []
      selector:
        action: {}
    bottom_off:
      name: Bottom (Off) Button Pressed
      description: "Execute when BOTTOM button is PRESSED"
      default: []
      selector:
        action: {}
    bottom_off_release:
      name: Bottom (Off) Button Released
      description: "Execute when BOTTOM button is RELEASED"
      default: []
      selector:
        action: {}
trigger:
  - platform: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: press
    subtype: 'on'
  - platform: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: press
    subtype: 'raise'
  - platform: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: press
    subtype: 'stop'
  - platform: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: press
    subtype: 'lower'
  - platform: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: press
    subtype: 'off'
  - platform: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: release
    subtype: 'on'
  - platform: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: release
    subtype: 'raise'
  - platform: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: release
    subtype: 'stop'
  - platform: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: release
    subtype: 'lower'
  - platform: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: release
    subtype: 'off'
condition: []
action:
  - choose:
      - conditions: '{{ trigger.event.data.action == "press" }}'
        sequence:
        - choose:
          - conditions: '{{ trigger.event.data.button_number == 2 }}'
            sequence: !input top_on
          - conditions: '{{ trigger.event.data.button_number == 5 }}'
            sequence: !input up_raise
          - conditions: '{{ trigger.event.data.button_number == 3 }}'
            sequence: !input middle_stop
          - conditions: '{{ trigger.event.data.button_number == 6 }}'
            sequence: !input down_lower
          - conditions: '{{ trigger.event.data.button_number == 4 }}'
            sequence: !input bottom_off

      - conditions: '{{ trigger.event.data.action == "release" }}'
        sequence:
        - choose:
          - conditions: '{{ trigger.event.data.button_number == 2 }}'
            sequence: !input top_on_release
          - conditions: '{{ trigger.event.data.button_number == 5 }}'
            sequence: !input up_raise_release
          - conditions: '{{ trigger.event.data.button_number == 3 }}'
            sequence: !input middle_stop_release
          - conditions: '{{ trigger.event.data.button_number == 6 }}'
            sequence: !input down_lower_release
          - conditions: '{{ trigger.event.data.button_number == 4 }}'
            sequence: !input bottom_off_release
    default: []
mode: !input auto_mode
max: !input mode_max
